controllers/ClientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Client;
use app\models\ClientSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends BaseController
{

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\ProductPrice;
use Yii;
use app\models\Product;
use app\models\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends BaseController
{

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();
        $postData = Yii::$app->request->post();
        if ($model->load($postData)) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $model->save();
                $pp = new ProductPrice();
                $pp->product_id = $model->getPrimaryKey();
                $pp->price = $postData['Product']['actualPrice'];
                $pp->save();
                $transaction->commit();
                return $this->redirect(['view', 'id' => $model->id]);
            } catch (\Exception $e) {
                $transaction->rollBack();
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $postData = Yii::$app->request->post();
        if ($model->load($postData)) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $model->save();
                $pp = new ProductPrice();
                $pp->product_id = $model->getPrimaryKey();
                $pp->price = $postData['Product']['actualPrice'];
                $pp->save();
                $transaction->commit();
            } catch (\Exception $e) {
                $transaction->rollBack();
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ServiceController.php
<?php

namespace app\controllers;

use app\models\Product;
use Yii;
use app\models\Service;
use app\models\ServiceSearch;
use yii\db\IntegrityException;
use yii\web\NotFoundHttpException;

/**
 * ServiceController implements the CRUD actions for Service model.
 */
class ServiceController extends BaseController
{

    /**
     * Lists all Service models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ServiceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Service model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $serviceModel = $this->findModel($id);

        if($product_id = Yii::$app->request->post('product_id')) {
            $product = Product::findOne($product_id);
            try {
                $serviceModel->link('products', $product);
            } catch(IntegrityException $e) {

            }

            return $this->redirect(['view', 'id' => $serviceModel->id]);
        }

        if($remove_product_id = Yii::$app->request->get('remove_product_id')) {
            $product = Product::findOne($remove_product_id);
            $serviceModel->unlink('products', $product, true);
            return $this->redirect(['view', 'id' => $serviceModel->id]);
        }

        $productsData = Product::getAvailableProducts();
        return $this->render('view', [
            'model' => $serviceModel,
            'productsData' => $productsData,
        ]);
    }

    /**
     * Creates a new Service model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Service();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Service model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Service model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Service model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Service the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Service::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/VisitInfoController.php
<?php

namespace app\controllers;

use app\models\Client;
use app\models\Service;
use Yii;
use app\models\VisitInfo;
use app\models\VisitInfoSearch;
use yii\db\IntegrityException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * VisitInfoController implements the CRUD actions for VisitInfo model.
 */
class VisitInfoController extends BaseController
{
    public $clientsData;

    public function getViewPath()
    {
        return '@app/views/visit';
    }

    public function init()
    {
        parent::init();
        $this->clientsData = Client::getAvailableClients();
    }

    /**
     * Lists all VisitInfo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VisitInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'clientsData' => $this->clientsData
        ]);
    }

    /**
     * Displays a single VisitInfo model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $session = Yii::$app->session;
        $visitModel = $this->findModel($id);

        if($service_id = Yii::$app->request->post('service_id')) {
            $service = Service::findOne($service_id);
            try {
                $visitModel->link('services', $service);
                $session->set('visit_status_update',[
                    'is_error' => false,
                    'message' => 'Услуга добавлена успешно'
                ]);
            } catch(IntegrityException $e) {
                $session->set('visit_status_update',[
                    'is_error' => true,
                    'message' => 'Ошибка! Выбранная услуга уже добавлена'
                ]);
            }

            return $this->redirect(['view', 'id' => $visitModel->id]);
        }

        if($remove_service_id = Yii::$app->request->get('remove_service_id')) {
            $service = Service::findOne($remove_service_id);
            $visitModel->unlink('services', $service, true);
            $session->set('visit_status_update',[
                'is_error' => false,
                'message' => 'Услуга успешно удалена из посещения'
            ]);
            return $this->redirect(['view', 'id' => $visitModel->id]);
        }


        if(!empty($_SESSION['visit_status_update'])){
            $visitStatusUpdate = $_SESSION['visit_status_update'];
            unset($_SESSION['visit_status_update']);
        }
        $serviceData = Service::getAvailableServices();
        return $this->render('view', [
            'model' => $visitModel,
            'clientsData' => $this->clientsData,
            'serviceData' => $serviceData,
            'visitStatusUpdate' => !empty($visitStatusUpdate) ? $visitStatusUpdate : null
        ]);
    }

    /**
     * Creates a new VisitInfo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VisitInfo();

        if($clientId = Yii::$app->request->get('client_id')) {
            $model->client_id = $clientId;
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'clientsData' => $this->clientsData,
        ]);
    }

    /**
     * Updates an existing VisitInfo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'clientsData' => $this->clientsData
        ]);
    }

    /**
     * Deletes an existing VisitInfo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the VisitInfo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return VisitInfo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VisitInfo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */

use yii\helpers\Html;
use \yiister\gentelella\widgets\Menu;
use \yii\widgets\Breadcrumbs;

$bundle = yiister\gentelella\assets\Asset::register($this);
\yii\web\JqueryAsset::register($this);
?>
<?php if (class_exists('yii\debug\Module')) {
    $this->off(\yii\web\View::EVENT_END_BODY, [\yii\debug\Module::getInstance(), 'renderToolbar']);
}?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link href="/css/site.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="nav-<?= !empty($_COOKIE['menuIsCollapsed']) && $_COOKIE['menuIsCollapsed'] == 'true' ? 'sm' : 'md' ?>">
<?php $this->beginBody(); ?>
<div class="container body">

    <div class="main_container">

        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">

                <div class="navbar nav_title" style="border: 0;">
                    <a href="/" class="site_title"><i class="logo-cosmet"></i> <span>Мой косметолог</span></a>
                </div>
                <div class="clearfix"></div>

                <!-- menu prile quick info -->
                <div class="profile">
                    <div class="profile_pic">
                        <img src="http://placehold.it/128x128" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Вы зашли как</span>
                        <h2><?= Yii::$app->user->isGuest ? '' : Yii::$app->user->identity->username ?></h2>
                    </div>
                </div>
                <!-- /menu prile quick info -->

                <br />

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3>General</h3>
                        <?=
                        Menu::widget(
                            [
                                "items" => [
                                    [
                                        "label" => "Главная",
                                        "url" => "/",
                                        "icon" => "home",
                                        'active' => \Yii::$app->controller->id == 'info'
                                    ],
                                    [
                                        "label" => "Клиенты",
                                        "url" => "/client/",
                                        "icon" => "group",
                                        'active' => \Yii::$app->controller->id == 'client'
//                                        "items" => [
//                                            [
//                                                "label" => "Список",
//                                                "url" => "/client/",
//                                            ],
//                                            [
//                                                "label" => "Создать",
//                                                "url" => "/client/create",
//                                            ],
//                                        ],
                                    ],
//                                    [
//                                        "label" => "Продукция",
//                                        "url" => "#",
//                                        "icon" => "table",
//                                        "items" => [
//                                            [
//                                                "label" => "Список",
//                                                "url" => "/product/",
//                                            ],
//                                            [
//                                                "label" => "Создать",
//                                                "url" => "/product/create",
//                                            ],
//                                        ],
//                                    ],
                                    [
                                        "label" => "Услуги",
                                        "url" => "/service/",
                                        "icon" => "medkit",
                                        'active' => \Yii::$app->controller->id == 'service'
//                                        "items" => [
//                                            [
//                                                "label" => "Список",
//                                                "url" => "/service/",
//                                            ],
//                                            [
//                                                "label" => "Создать",
//                                                "url" => "/service/create",
//                                            ],
//                                        ],
                                    ],
                                    [
                                        "label" => "Посещения",
                                        "url" => "/visit-info/",
                                        "icon" => "calendar",
                                        'active' => \Yii::$app->controller->id == 'visit-info'
//                                        "items" => [
//                                            [
//                                                "label" => "Список",
//                                                "url" => "/visit-info/",
//                                            ],
//                                            [
//                                                "label" => "Создать",
//                                                "url" => "/visit-info/create",
//                                            ],
//                                        ],
                                    ],
                                ],
                            ]
                        )
                        ?>
                    </div>

                </div>
                <!-- /sidebar menu -->

            </div>
        </div>

        <!-- top navigation -->


            <div class="nav_menu scroll-fixed">
                <div class="top_nav">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
<!--                                    <img src="http://placehold.it/128x128" alt="">-->
                                    <?= Yii::$app->user->isGuest ? '' : Yii::$app->user->identity->username ?>
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li>
                                        <?= Html::a('<i class="fa fa-sign-out pull-right"></i> Выйти',
                                            '/site/logout', [
                                                'data' => [
                                                    'method' => 'post',
                                                ],
                                            ]) ?>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                </div>
            </div>


        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col cosmet-main-cont" role="main">
            <?php if (isset($this->params['h1'])): ?>
                <div class="page-title">
                    <div class="title_left">
                        <h1><?= $this->params['h1'] ?></h1>
                    </div>
                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <?= Breadcrumbs::widget(['links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],]);?>
            <div class="clearfix"></div>

            <?= $content ?>
        </div>
        <!-- /page content -->
        <!-- footer content -->
        <footer>
            <div class="pull-right my-cosmet">
                Система CRM Мой Косметолог<br />
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>

</div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>
<script>
    var windowAppSize = {
        dWidth: $(document).width(),
        bWidth: $('body').width(),
        init: function(){
            if(this.dWidth > this.bWidth) {
                $('body').width(this.dWidth + 30)
            }
        }
    };
    windowAppSize.init();
    <?if (Yii::$app->user->id === 1 || Yii::$app->user->id === 2) {
        // Это короче злой сюрприз-функционал. Жмякаем 4 раза на "мой косметолог" ->
        // врубаем или вырубаем телефоны на всем сайте
        ?>
        $(document).ready(function(){
            var timer,
                message = <?= json_encode(Yii::$app->user->identity->isPhoneEnabled() ? 'Скрыть телефоны?' : 'Отобразить телефоны?') ?>,
                clickCount = 0;
            $('footer .my-cosmet').on('click',function(){
                if(!timer) {
                    timer = setTimeout(function(){
                        clickCount = 0;
                        timer = null;
                    }, 2000);
                }
                clickCount++;
                if(clickCount>4) {
                    var c = confirm(message);
                    if(c) {
                        location.href = '/info/turn/';
                    }
                }
            })
        });
    <? }?>
</script>

views/layouts/site.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\site\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';

$bundle = yiister\gentelella\assets\Asset::register($this);

$this->beginPage(); ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <!-- Bootstrap -->
        <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- Animate.css -->
        <link href="https://colorlib.com/polygon/gentelella/css/animate.min.css" rel="stylesheet">

        <!-- Custom Theme Style -->
        <link href="../build/css/custom.min.css" rel="stylesheet">
        <link href="/css/site.css" rel="stylesheet">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta charset="<?= Yii::$app->charset ?>" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body class="login">
    <?php $this->beginBody(); ?>
        <div class="body-wrapper">
            <?= $content ?>
        </div>
    <?php $this->endBody(); ?>
    </body>
    </html>
<?php $this->endPage(); ?>